name: base
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - traitlets>=4.3.1
  - ipython
  - vdom
  - jupyterlab_launcher>=0.5.0
  - jupyterlab=1.2.1 
  - voila 
  - jupyterlab-git
  - pip:
    - nbinteract 

