#!/bin/bash

# Install JupyterLab extensions
jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.0 --no-build
jupyter labextension install   @jupyterlab/celltags --no-build
jupyter labextension install   @jupyterlab/toc --no-build
jupyter labextension install   @jupyterlab/geojson-extension jupyterlab-drawio --no-build
jupyter labextension install   @jupyter-voila/jupyterlab-preview --no-build

jupyter serverextension enable --py jupyterlab_git

jupyter lab build
