name: Build and deploy Docker app to the Azure container registry

on: push

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# Set up the following secrets in your repository:
#   AZURE_CREDENTIALS, REGISTRY_USERNAME, REGISTRY_PASSWORD, AZURE_DEVOPS_TOKEN
# 2. Change these variables for your configuration:
env:
  AZURE_RESOURCE_GROUP: ActionsDemo   # set this to your Azure Resource group's name  
  CONTAINER_REGISTRY: jamesjnadeaujupyter.azurecr.io   # set this to Container Registry name

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
            
   # Authentication
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Build and push
    - run: |
        docker build ./binder/Dockerfile -t ${{ env.CONTAINER_REGISTRY }}/binder:${{ github.sha }}
        docker push ${{ env.CONTAINER_REGISTRY }}/binder:${{ github.sha }}
    
    # Deploy
    # - uses: azure/webapps-container-deploy@v1
    #   with:
    #     app-name: 'jupyter-lab'
    #     images: '${{ env.CONTAINER_REGISTRY }}/binder:${{ github.sha }}'
    
    # Logout
    - name: Azure logout
      run: |
        az logout
        